//! The kernel schema has one canonical form, and both sides of a crate boundary read it.
//!
//! `smysl-provider` translates this schema for OpenAI's strict mode and for Gemini's dialect,
//! so it needs the schema to test against — and it cannot depend on `smysl-ingest`, because
//! ingest depends on the provider and that is the cycle. It kept an inline copy instead.
//!
//! By 0.14 the copy had drifted to 2 of the 13 kernel types, 2 of the 5 statuses, 1 of the 3
//! conditionals and a different `label` pattern, while `openai.rs` documented its tests as
//! running "against the full Appendix C schema rather than a miniature of it". Nothing could
//! have caught that: the two definitions had no way to meet.
//!
//! `fixtures/schema/unit.json` is where they meet now. This end asserts the file still is what
//! the generator emits; the provider end translates that file and asserts the result is
//! strict-legal at every object. A change to one that is not a change to both fails here.
//!
//! Compared as bytes rather than as parsed JSON, deliberately: `smysl-ingest` links no JSON
//! parser and should not gain one for a test. The file is generated by the function it is
//! compared against, so byte equality is the right relation — this is a golden file, and the
//! value of a golden file is that a diff is a decision.

const FIXTURE: &str = "../../fixtures/schema/unit.json";

#[test]
fn schema_fixture_matches_the_generator() {
    let generated = smysl_ingest::schema::unit_schema();
    let on_disk = std::fs::read_to_string(FIXTURE)
        .expect("fixtures/schema/unit.json must exist; smysl-provider tests against it");

    if generated != on_disk {
        let g: Vec<&str> = generated.lines().collect();
        let d: Vec<&str> = on_disk.lines().collect();
        let first = g
            .iter()
            .zip(d.iter())
            .position(|(a, b)| a != b)
            .unwrap_or(g.len().min(d.len()));
        panic!(
            "the schema changed and fixtures/schema/unit.json did not.\n\
             First difference at line {}:\n  generated: {}\n  on disk:   {}\n\n\
             If the change was deliberate, write `smysl_ingest::schema::unit_schema()` to that \
             path and re-run the provider's Appendix C tests — they translate this exact file \
             for OpenAI's strict mode.",
            first + 1,
            g.get(first).unwrap_or(&"<end of file>"),
            d.get(first).unwrap_or(&"<end of file>"),
        );
    }
}

/// The claim the drift falsified, asserted so it cannot be made falsely again.
///
/// `openai.rs` documents its strict-mode tests as running against the *full* Appendix C
/// schema. Full means every kernel type and every status the format defines, not a readable
/// subset — the copy it replaced had two of each.
#[test]
fn the_fixture_is_the_whole_schema_and_not_a_miniature() {
    let s = std::fs::read_to_string(FIXTURE).expect("the fixture");

    for t in smysl_ingest::schema::authorable_types() {
        assert!(
            s.contains(&format!("\"{t}\"")),
            "kernel type `{t}` is missing from the schema fixture"
        );
    }
    for st in smysl_ingest::schema::authorable_statuses() {
        assert!(
            s.contains(&format!("\"{st}\"")),
            "status `{st}` is missing from the schema fixture"
        );
    }
    assert!(
        smysl_ingest::schema::authorable_types().len() >= 13,
        "the format defines at least thirteen kernel types; a shrinking list is the drift \
         this test exists to catch"
    );
}
