[package]
name = "smysl-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
smysl-core = { path = "../crates/smysl-core" }

[[bin]]
name = "surface"
path = "fuzz_targets/surface.rs"
test = false
doc = false

[[bin]]
name = "cbor"
path = "fuzz_targets/cbor.rs"
test = false
doc = false
